name: Deploy

on:
  workflow_dispatch:

env:
  BUCKET_NAME: "task-6-2"
  AWS_REGION: "ap-northeast-1"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow URL to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "Terraform Apply! 請幫忙 Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

  terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::827072983716:role/task-6-2-role
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform_apply:
    environment: production
    needs: terraform_plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218138280714:role/task-6-2-role
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
