name: PR Check And Plan

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'

env:
  BUCKET_NAME: "task-6-2"
  AWS_REGION: "ap-northeast-1"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::827072983716:role/task-6-2-role
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Show Plan
        id: showplan
        run: |
          terraform plan -no-color > plan.txt

      - name: Upload Plan Output as PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ${{ github.workspace }}/src/plan.txt
